unicodeveloper/awesome-opensource-apps

README.md

made modifications
links now point to github repo

Meteor branch

---

README.md

- This explains how you write good documentation on laravel framework.
- I remove "/" on some link and "." to adjust other list

Add laravel.com & fix typo

---

README.md

I think conflicts are fixed now

Add Wekan source code

---

README.md

Added ["Wallsplash"](https://github.com/mikepenz/wallsplash-android) to the Android section.

Added "Wallsplash" to the Android section.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unicodeveloper/awesome-opensource-apps/16)

Add Condor server monitor

---

.gitignore
README.md

@unicodeveloper 
Added "[DevTv](https://github.com/iamraphson/DEV-TV)" to the Laravel section and added reactJS section

Added "DevTv" to the Laravel section and added reactJS section

---

README.md

@unicodeveloper 
Kindly do the needful

Add 2 awesome applications

---

README.md

A simple way to block access to the internet per application - http://www.netguard.me/
https://github.com/M66B/NetGuard

Add NetGuard to android section

---

README.md

A collection of open source projects built using Laravel.

Add openlaravel

---

README.md

Thanks for sharing it on your repo.

update Antvel link

---

README.md

IgniCMS:
- New URL
- New tagline

Updated IgniCMS's link with the new (correct) one.

---

README.md

This is a diary application optimized to user experience.
I hope my project useful for beginner developer.

Added simple diary application into android category

---

README.md

Closes #34
Related links:
* https://crystal-lang.org/
* https://amberframework.org/
* https://crystal-ann.com/
* https://github.com/crystal-community/crystal-ann

Amber section and Crystal ANN

---

README.md

Added password management application into android category

Added password management application into android category

---

README.md

Added a C# library for seamless MySQL connection and CRUD operations in the database.

Added another awesome tool

---

README.md

Add Ulangi

---

README.md

I've just mentioned wrapper written in Vue.js and ReactJS for the [Handsontable ](https://github.com/handsontable/handsontable)spreadsheet component.

Add Handsontable Vue.js and ReactJs wrappers

---

README.md

Remove VotePen

---

README.md

This PR adds Dnote which is a free and open source note-taking application built with React.
* https://github.com/dnote/dnote

Add Dnote to ReactJS section

---

README.md

[one-stop post about this app](https://www.reddit.com/r/androidapps/comments/i30tpp/instagrabber_an_open_source_instagram_client/)

Add InstaGrabber

---

README.md

Update README.md ADD Lavendel to electron apps

---

README.md

PopCritic is a movie review website which is focussed on various aspects of films and help people find the best film to watch next.
Web App: https://popcritic.web.app/
GitHub: https://github.com/theabbie/PopCritic

Add PopCritic to ReactJS

---

README.md

Taskord is free open source social media for tasks! where users can post public and private todos, ask questions, and launch products. Taskord helps you to get things done together with the members of the community.
It is a production level project with perfect codebase.
Prod URL: https://taskord.com
Codebase: https://gitlab.com/taskord/taskord

Add Taskord to Laravel

---

README.md

added new link under ReactJs

---

README.md

Added two sites links
